### ISSUE TITLE
Additional Providers and currently airing shows 

### ISSUE THREAD

**Issue by ItzNuggetz** [rhenwinch/Flixclusive#71]
### Steps to reproduce

1. I'm on the pre release but some of the shows like Panchayat which is from Amazon prime says this is not playable. 
2. There are other shows which might show up on Flix but due to absence of meta data or the content being removed from the site doesn't play at all
3. Episodes names are missing for currently airing or recent TV show. 
![Screenshot_20240608_235731](https://github.com/rhenwinch/Flixclusive/assets/166253246/d5d0b185-4061-465a-b080-662b9e58d0fd)

### Expected behavior

Shows, movies or old cartoons should play with proper episode names 

### Actual behavior

Most of the currently airing content or Asian TV shows have no episode names on them instead they are marked as Episode 1, then Episode 2 and all the way goes down. Many shows won't play probably because of the content being removed or for a meta data unavailability. 

### Flixclusive version

1.4.0 b8e01f7

### Android version

Android 13

### Device

Honor 90

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
Hey,

> There are other shows which might show up on Flix but due to absence of meta data or the content being removed from the site doesn't play at all

I'll be introducing a catalog system for providers soon. I hope this fixes it. I know TMDB is community maintained and some films might not be available there, especially if it's not well-known in US or anywhere in the world.

> Episodes names are missing for currently airing or recent TV show.

As I've said, TMDB is a community maintained database of movies/shows. Not all episodes have been named by the maintainers so it resorts back to the _"Episode number"_ format as a placeholder. In general, _the app can't do nothing about this anymore._

> I'm on the pre release but some of the shows like Panchayat which is from Amazon prime says this is not playable.

Sounds like a provider-related issue. Can you check this [issue](https://github.com/Flixclusive/flx-providers/issues/8) if the links provided have all the Hindi films you've like to watch?

Also, the show 'Panchayat' has an issue where the app crashes because it cannot properly format the date of the show. Idk if you know this but you might just have unconsciously raised an issue about this too - thanks!

In the meantime, I'll be closing this one for now since this issue seems to be a provider-related issue, which are found here: [Flixclusive/flx-providers](https://github.com/Flixclusive/flx-providers/issues/)
