### ISSUE TITLE
Unable to see new ep 

### ISSUE THREAD

**Issue by injusticedevil** [rhenwinch/Flixclusive#81]
### Steps to reproduce

![Uploading Screenshot_2024-06-20-21-33-15-297_com.flixclusive.jpg…]()

### Expected behavior

Hope it gets fixed in the next update 

### Actual behavior

I tried to watch the new boys ep and when I tried to watch it it says failed to fetch share key for superstream hope u fix it soon 

### Flixclusive version

Latest pre release 

### Android version

11

### Device

Poco m2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by injusticedevil** [comment]
Also plz tell me which stremio addon is currently working thank you

**Comment by injusticedevil** [comment]
![Uploading Screenshot_2024-06-20-21-33-15-297_com.flixclusive.jpg…]()

**Comment by rhenwinch** [comment]
Hi, appreciate the concern.

> It says failed to fetch share key for superstream hope u fix it soon

The provider issue you've mentioned is fixed on commit https://github.com/Flixclusive/flx-providers/commit/cd3824af5439a2659973696437ebd57c427e100d as well as https://github.com/rhenwinch/Flixclusive/commit/51f8d26cd7d978fd7a0e27ab12442ffa92934a40.

> Also plz tell me which stremio addon is currently working thank you

So far, I've tried Torrentio + RD, JaMovies and Shluflix. Torrentio with RealDebrid is just heaven sent; _no lags or whatsoever_.
- https://torrentio.strem.fun/configure
- https://eja-addon.vercel.app/
- https://shluflix.elfhosted.com/

---
Also, if you haven't noticed yet, all providers issue should be opened up or migrated to their own respective repositories, since SuperStream is Flixclusive's built-in provider refer [here](https://github.com/Flixclusive/flx-providers) next time in the future if you've ever encountered more problems.

Thanks
